name: google cloud

on:
  push:
    branches:
      - main

env:
  GCP_REGION: asia-northeast1
  JOB_NAME: sample-job
  CONTAINER_NAME: sample-job
  REPOSITORY_NAME: asia-northeast1-docker.pkg.dev/hobby-383808/deploy-cloud-run-job-example

jobs:
  gsls:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jobs/python/sample-job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.google_cloud_workload_identity_provider }}
          service_account: ${{ secrets.google_cloud_oidc_account }}

      - run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run: docker build -t ${CONTAINER_NAME} .
      - run: docker tag ${CONTAINER_NAME}:latest ${REPOSITORY_NAME}/${CONTAINER_NAME}:latest
      - run: gcloud run deploy ${SERVICE} --image ${REPOSITORY_NAME}/${CONTAINER_NAME}:latest --region ${GCP_REGION}
