name: google cloud

on:
  push:
    branches:
      - main

env:
  GCP_REGION: asia-northeast1
  JOB_NAME: sample-job
  CONTAINER_NAME: sample-job
  REPOSITORY_NAME: asia-northeast1-docker.pkg.dev/hobby-383808/deploy-cloud-run-job-example

jobs:
  gsls:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: jobs/python/sample-job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }} | wc -c
      - run: echo ${{ secrets.GOOGLE_CLOUD_OIDC_ACCOUNT }} | wc -c
      - uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}=
          service_account: ${{ env.GOOGLE_CLOUD_OIDC_ACCOUNT }}

      - run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run: docker build --build-arg="MODULE_PATH_TO_EXECUTE=main" -t ${CONTAINER_NAME} .
      - run: docker tag ${CONTAINER_NAME}:latest ${REPOSITORY_NAME}/${CONTAINER_NAME}:latest
      - run: docker push ${REPOSITORY_NAME}/${CONTAINER_NAME}:latest
      - run: gcloud run jobs deploy ${JOB_NAME} --image ${REPOSITORY_NAME}/${CONTAINER_NAME}:latest --region ${GCP_REGION}
